### ISSUE TITLE
JPEGView not displaying all the embedded metadata in JPEGs

### ISSUE THREAD

**Issue by Flavored-37860** [sylikc/jpegview#207] opened 2023-06-10 21:39 UTC
JPEGView shows only very limited data but not all of it that EXIF Tool or other image viewers can display
Image I used for this can be downloaded from here.. https://i.postimg.cc/0jLbYZpn/DSCN0012.jpg

Here's how [HoneyView](https://www.bandisoft.com/honeyview/) displays EXIF info:
![Ercz6o8fs0](https://github.com/sylikc/jpegview/assets/92237041/553b4d70-8eb8-47c5-80f3-1c7d9ebc9101)

Here's what JPEGView shows:
![E5ILsrFd8J](https://github.com/sylikc/jpegview/assets/92237041/624699ad-5ae4-40f4-9d87-332fcb4064bc)

Here's how much [EXIF Tool](https://exiftool.org/) can show:
![iVGEaKIRWI](https://github.com/sylikc/jpegview/assets/92237041/7c8b1fbe-ee13-4946-8444-351f54d5dbc3)

please fix it!

**Comment by sylikc** [comment] 2023-06-15 11:49
JPEGView currently doesn't use any libraries to parse the EXIF data.  It only shows some of the basic data at this time, though it would be a good future enhancement.

(This is a partial duplicate of #72 )  I tried to add XPComment to the Comment field unsuccessfully.  EXIF structure is pretty complex, and there are multiple places where tags can be... I'd need some help from other devs to see if it can be done without adding in a library, or convert the EXIF reading to use a fast library.

**Closed** 2023-06-29 08:07 UTC
Labels: enhancement, help wanted, format support
