### ISSUE TITLE
Suggestions and wishes

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [sylikc/jpegview#52] opened 2022-04-02 01:47 UTC
### Suggestions and wishes

- When viewed with the "FolderNavigation=LoopFolder" and "WrapAroundFolder=false" parameters, there is no visual effect that the images in the folder have ended.
- No option to select image quality when saving.

Assign by default:
- Middle mouse button to close the program, convenient using only the mouse.
- "FileDisplayOrder=FileName", because in Windows Explorer default sorting is by file name. It is better that Jpegview determines in which mode the sorting occurs in the explorer and uses it accordingly when viewing.
- "IniEditor=system" because a lot of people don't use notepad, they use third party programs.

P.S. Sorry for my google translate )

**Comment by sylikc** [comment] 2022-04-02 19:48
> * "FileDisplayOrder=FileName", because in Windows Explorer default sorting is by file name. It is better that Jpegview determines in which mode the sorting occurs in the explorer and uses it accordingly when viewing.

I'm considering making that default, as per the PR https://github.com/sylikc/jpegview/pull/22



> * Middle mouse button to close the program, convenient using only the mouse.

This, I probably wouldn't implement myself... I actually use the middle mouse button very frequently on windows for many tasks... and scrolling is the default on most windows, so probably this wouldn't come



> * "IniEditor=system" because a lot of people don't use notepad, they use third party programs.

I'll take this into account during the ini system redesign... I have a lot of ideas for it... not just the editor, but the weird hierarchy that is in play now.  More details of that to come... i'm still designing it... i've been designing it and thinking about it for a few weeks...

**Comment by sylikc** [comment] 2023-02-12 22:53
Current status of these feature requests:

> * When viewed with the "FolderNavigation=LoopFolder" and "WrapAroundFolder=false" parameters, there is no visual effect that the images in the folder have ended.

Added one visual feedback, and one audio feedback mechanism...  https://github.com/sylikc/jpegview/commit/ef680cb194505af30cc3b07d2b69ed2698accfd9

> * No option to select image quality when saving.

Duplicate of #82

> Assign by default:
> 
> * Middle mouse button to close the program, convenient using only the mouse.

Probably won't ever set to default... but you can change this in your `KeyMap.txt`  Copy the KeyMap.txt.default and add a line
```
MouseM           IDM_EXIT
```

> * "FileDisplayOrder=FileName", because in Windows Explorer default sorting is by file name. It is better that Jpegview determines in which mode the sorting occurs in the explorer and uses it accordingly when viewing.
> * "IniEditor=system" because a lot of people don't use notepad, they use third party programs.

Both of these will be considered in a discussion #140

**Closed by sylikc** 2023-02-12 22:53 UTC
Labels: enhancement
