### ISSUE TITLE
Is it possible to disable image filtering on zoom?

### ISSUE THREAD

**Issue by alexgoulden** [sylikc/jpegview#192] opened 2023-05-10 12:01 UTC
I went digging through the user settings and came up blank, I'm attempting to set it so when an image is zoomed in no anti-aliasing is applied, so the pixels when up-scaled don't blend together. Basically keep it as it looks for a split second when you increase the zoom in the app currently

**Comment by sylikc** [comment] 2023-05-10 18:04
So, this was previously asked before, I think... let me know if this is a duplicate of #19

I had created a branch with code to test this.  I didn't merge it because no one replied on that thread.

See https://github.com/sylikc/jpegview/issues/19#issuecomment-1455124096 if it is what you want, and I'll merge it in

**Comment by vv** [comment] 2023-05-14 20:25
You can toggle resampling using F3 key.

**Comment by sylikc** [comment] 2023-05-18 19:04
Right, you can toggle it off entirely, but I can understand their use case to only have it off zooming in.

I'll merge that branch soon. (Life happened but my time is freeing up again)

**Comment by sylikc** [comment] 2023-10-06 12:25
This is resolved I believe

**Closed as completed by sylikc** 2023-10-06 12:25 UTC
Labels: duplicate, enhancement, question
